spring:

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 2017253008

  redis:
    port: 6379
    host: localhost

  jpa:
    hibernate:
      ddl-auto: create